package katering;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ihul
 */
public class beranda extends javax.swing.JFrame {
    
    menu barang;
    /**
     * Creates new form beranda
     */
    public beranda() {
        initComponents();
        isiKomboMenu();
    }
    
    private void isiKomboMenu(){
        menu menu1 = new menu("Susu", 11000);
        menu menu2 = new menu("Rokok", 16000);
        menu menu3 = new menu("Snack", 6500);
        menu menu4 = new menu("Sabun", 2000);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        btnMenu2 = new javax.swing.JButton();
        btnMenu3 = new javax.swing.JButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        PnlMenu1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        judulTambahPesanan = new javax.swing.JLabel();
        komboBoxMenu = new javax.swing.JComboBox<>();
        txtMenu = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        tmblTambah1 = new javax.swing.JButton();
        tmblHapus1 = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        txtBayar = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        txtKembali = new javax.swing.JLabel();
        tmblCetak = new javax.swing.JButton();
        PnlMenu2 = new javax.swing.JPanel();
        judulMenu = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        txtTambahMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tmblTambah = new javax.swing.JButton();
        tmblHapus2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PnlMenu3 = new javax.swing.JPanel();
        judulMenu1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMenu1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        btnMenu1.setBackground(new java.awt.Color(217, 128, 38));
        btnMenu1.setFont(new java.awt.Font("Axis", 0, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setText("PESAN");
        btnMenu1.setBorder(null);
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        btnMenu2.setBackground(new java.awt.Color(217, 128, 38));
        btnMenu2.setFont(new java.awt.Font("Axis", 0, 18)); // NOI18N
        btnMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu2.setText("MENU");
        btnMenu2.setBorder(null);
        btnMenu2.setBorderPainted(false);
        btnMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });

        btnMenu3.setBackground(new java.awt.Color(217, 128, 38));
        btnMenu3.setFont(new java.awt.Font("Axis", 0, 18)); // NOI18N
        btnMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu3.setText("RIWAYAT");
        btnMenu3.setBorder(null);
        btnMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addComponent(btnMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        PnlMenu1.setBackground(new java.awt.Color(255, 255, 255));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBarang);
        if (tblBarang.getColumnModel().getColumnCount() > 0) {
            tblBarang.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tblBarang.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        judulTambahPesanan.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        judulTambahPesanan.setForeground(new java.awt.Color(255, 153, 51));
        judulTambahPesanan.setText("TAMBAH PESANAN");

        komboBoxMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        komboBoxMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komboBoxMenuActionPerformed(evt);
            }
        });

        txtMenu.setFont(new java.awt.Font("Axis", 0, 14)); // NOI18N
        txtMenu.setForeground(new java.awt.Color(102, 102, 102));
        txtMenu.setText("MENU");

        txtHarga.setFont(new java.awt.Font("Axis", 0, 14)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(102, 102, 102));
        txtHarga.setText("HARGA");

        txtJumlah.setFont(new java.awt.Font("Axis", 0, 14)); // NOI18N
        txtJumlah.setForeground(new java.awt.Color(102, 102, 102));
        txtJumlah.setText("JUMLAH");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        tmblTambah1.setBackground(new java.awt.Color(255, 153, 51));
        tmblTambah1.setForeground(new java.awt.Color(255, 255, 255));
        tmblTambah1.setText("TAMBAH");

        tmblHapus1.setBackground(new java.awt.Color(255, 153, 51));
        tmblHapus1.setForeground(new java.awt.Color(255, 255, 255));
        tmblHapus1.setText("HAPUS");
        tmblHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblHapus1ActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 153, 51));
        txtTotal.setText("TOTAL   :");

        txtBayar.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        txtBayar.setForeground(new java.awt.Color(255, 153, 51));
        txtBayar.setText("BAYAR   :");

        bayar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bayar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        txtKembali.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        txtKembali.setForeground(new java.awt.Color(255, 153, 51));
        txtKembali.setText("KEMBALI :");

        tmblCetak.setBackground(new java.awt.Color(255, 153, 51));
        tmblCetak.setForeground(new java.awt.Color(255, 255, 255));
        tmblCetak.setText("CETAK");
        tmblCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlMenu1Layout = new javax.swing.GroupLayout(PnlMenu1);
        PnlMenu1.setLayout(PnlMenu1Layout);
        PnlMenu1Layout.setHorizontalGroup(
            PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulTambahPesanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlMenu1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMenu1Layout.createSequentialGroup()
                        .addComponent(txtKembali)
                        .addGap(675, 675, 675)
                        .addComponent(tmblCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMenu1Layout.createSequentialGroup()
                        .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlMenu1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tmblHapus1))
                            .addGroup(PnlMenu1Layout.createSequentialGroup()
                                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlMenu1Layout.createSequentialGroup()
                                        .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jumlah)
                                            .addGroup(PnlMenu1Layout.createSequentialGroup()
                                                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtJumlah)
                                                    .addComponent(tmblTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHarga)
                                                    .addComponent(txtTotal))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(59, 59, 59))
                                    .addGroup(PnlMenu1Layout.createSequentialGroup()
                                        .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(komboBoxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMenu)
                                            .addGroup(PnlMenu1Layout.createSequentialGroup()
                                                .addComponent(txtBayar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        PnlMenu1Layout.setVerticalGroup(
            PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(judulTambahPesanan)
                .addGap(11, 11, 11)
                .addComponent(tmblHapus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlMenu1Layout.createSequentialGroup()
                        .addComponent(txtMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(komboBoxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtHarga)
                        .addGap(44, 44, 44)
                        .addComponent(txtJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(tmblTambah1)
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTotal)
                .addGap(4, 4, 4)
                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKembali)
                    .addComponent(tmblCetak))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PnlMenu1, "card2");

        PnlMenu2.setBackground(new java.awt.Color(255, 255, 255));

        judulMenu.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        judulMenu.setForeground(new java.awt.Color(255, 153, 51));
        judulMenu.setText("MENU MAKANAN & MINUMAN");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Menu", "Nama", "Harga", "Total Pesanan"
            }
        ));
        jScrollPane3.setViewportView(tblMenu);

        txtTambahMenu.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        txtTambahMenu.setForeground(new java.awt.Color(255, 153, 51));
        txtTambahMenu.setText("TAMBAH MENU");

        jLabel1.setFont(new java.awt.Font("Axis", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("NAMA");

        jLabel2.setFont(new java.awt.Font("Axis", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("HARGA");

        tmblTambah.setBackground(new java.awt.Color(255, 153, 51));
        tmblTambah.setForeground(new java.awt.Color(255, 255, 255));
        tmblTambah.setText("TAMBAHKAN");

        tmblHapus2.setBackground(new java.awt.Color(255, 153, 51));
        tmblHapus2.setForeground(new java.awt.Color(255, 255, 255));
        tmblHapus2.setText("HAPUS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlMenu2Layout = new javax.swing.GroupLayout(PnlMenu2);
        PnlMenu2.setLayout(PnlMenu2Layout);
        PnlMenu2Layout.setHorizontalGroup(
            PnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulMenu)
                    .addComponent(tmblHapus2)
                    .addGroup(PnlMenu2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(PnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTambahMenu)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmblTambah)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        PnlMenu2Layout.setVerticalGroup(
            PnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulMenu)
                .addGap(42, 42, 42)
                .addGroup(PnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMenu2Layout.createSequentialGroup()
                        .addComponent(txtTambahMenu)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(tmblTambah))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmblHapus2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PnlMenu2, "card3");

        PnlMenu3.setBackground(new java.awt.Color(255, 255, 255));

        judulMenu1.setFont(new java.awt.Font("Axis", 0, 24)); // NOI18N
        judulMenu1.setForeground(new java.awt.Color(255, 153, 51));
        judulMenu1.setText("RIWAYAT PESANAN");

        tblMenu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pesanan", "Tanggal", "Menu (Jumlah)", "Total Harga", "Nota Transaksi"
            }
        ));
        jScrollPane4.setViewportView(tblMenu1);

        javax.swing.GroupLayout PnlMenu3Layout = new javax.swing.GroupLayout(PnlMenu3);
        PnlMenu3.setLayout(PnlMenu3Layout);
        PnlMenu3Layout.setHorizontalGroup(
            PnlMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulMenu1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        PnlMenu3Layout.setVerticalGroup(
            PnlMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenu3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(judulMenu1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PnlMenu3, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        PnlMenu1.setVisible(false);
        PnlMenu2.setVisible(true);
        PnlMenu3.setVisible(false);
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        PnlMenu1.setVisible(true);
        PnlMenu2.setVisible(false);
        PnlMenu3.setVisible(false);
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu3ActionPerformed
        PnlMenu1.setVisible(false);
        PnlMenu2.setVisible(false);
        PnlMenu3.setVisible(true);
    }//GEN-LAST:event_btnMenu3ActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void tmblHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblHapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmblHapus1ActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tmblCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblCetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmblCetakActionPerformed

    private void komboBoxMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komboBoxMenuActionPerformed
        barang = (menu)komboBoxMenu.getSelectedItem();
    }//GEN-LAST:event_komboBoxMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu1;
    private javax.swing.JPanel PnlMenu2;
    private javax.swing.JPanel PnlMenu3;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnMenu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel judulMenu;
    private javax.swing.JLabel judulMenu1;
    private javax.swing.JLabel judulTambahPesanan;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> komboBoxMenu;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblMenu1;
    private javax.swing.JButton tmblCetak;
    private javax.swing.JButton tmblHapus1;
    private javax.swing.JButton tmblHapus2;
    private javax.swing.JButton tmblTambah;
    private javax.swing.JButton tmblTambah1;
    private javax.swing.JLabel txtBayar;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtJumlah;
    private javax.swing.JLabel txtKembali;
    private javax.swing.JLabel txtMenu;
    private javax.swing.JLabel txtTambahMenu;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
